### ISSUE TITLE
Ability to change the interval for logging in ResourceMonitor.csv

### ISSUE THREAD

**Issue by gautamzone** [mafranks/CiscoSecureEndpointResourceMonitorCSharp#6]
Can we modify the interval for logging from 1 sec to something more like 1 minute or even more?
Logging CPU every 1 sec is great for real-time troubleshooting but for those looking for a summary of CPU usage, they could use larger intervals.

Thanks!
Gautam

**Comment by mafranks** [comment]
Resolved with latest push.  Added options for every cycle, 30 seconds, every minute and every 5 minutes.
